Repository hanami/hanami, pull requests merged in 2018-10, with the labels that each got.

#957 Only pass app body parsers options to internal router if user enables them
  lib/hanami/components/app/routes.rb
Labels: enhancement

#956 use <= instead of ancestors.include? for performance reasons
  README.md
  lib/hanami/components/routes_inspector.rb
  lib/hanami/configuration.rb
Labels: enhancement

#959 Generate correct syntax for layout unit tests
  lib/hanami/cli/commands/generate/app/layout_spec.minitest.erb
  lib/hanami/cli/commands/generate/app/layout_spec.rspec.erb
  spec/integration/cli/generate/app_spec.rb
  spec/integration/cli/new/test_spec.rb
Labels: fix

#952 Fix concatenation of Pathname and String in CommonLogger
  lib/hanami/common_logger.rb
Labels: bug, fix
