Repository hanami/hanami, pull requests merged in 2018-02, with the labels that each got.

#896 Generate new projects with `hanami-webconsole` gem
  Gemfile
  lib/hanami/cli/commands/new/Gemfile.erb
  script/setup
  script/teardown
  spec/integration/cli/new_spec.rb
Labels: feature

#868 raise error if config/environment.erb miss necessary environment valuable
  lib/hanami/cli/commands/new/config/environment.erb
  spec/integration/cli/new_spec.rb
  spec/support/shared_examples/cli/generate/app.rb
Labels: enhancement

#899 Create simple one file template for hanami model with sqlite adapter
  templates/model_sqlite.rb
Labels: enhancement

#905 Early Hints
  lib/hanami/app.rb
  lib/hanami/configuration.rb
  lib/hanami/early_hints.rb
  spec/integration/early_hints_spec.rb
  spec/unit/early_hints_spec.rb
Labels: feature

#866 Render 500 custom template if an exception happens in a view or template
  .rubocop.yml
  lib/hanami/application_configuration.rb
  lib/hanami/rendering_policy.rb
  spec/integration/handle_exceptions_spec.rb
Labels: fix
