Repository hanami/hanami, pull requests merged in 2018-04, with the labels that each got.

#861 Avoid using Hanami::Utils.reload! when code_reloading is disabled
  lib/hanami/components/components.rb
Labels: bug, fix

#875 Handle exceptions at the project level
  lib/hanami/app.rb
  lib/hanami/app/router.rb
  lib/hanami/application_configuration.rb
  lib/hanami/cli/commands/generate/app/application.erb
  lib/hanami/cli/commands/new/config/environment.erb
  lib/hanami/components/app/controller.rb
  lib/hanami/configuration.rb
  lib/hanami/renderer.rb
  lib/hanami/views/default.rb
  spec/integration/cli/new_spec.rb
  spec/integration/exceptions_handling_spec.rb
  spec/integration/handle_exceptions_spec.rb
  spec/integration/middleware_spec.rb
  spec/integration/sessions_spec.rb
  spec/support/shared_examples/cli/generate/app.rb
Labels: breaking-change, feature

#926 Generate new projects with dotenv ~> 2.4
  Gemfile
  lib/hanami/cli/commands/new/Gemfile.erb
  spec/integration/cli/new_spec.rb
Labels: fix
