Repository hanami/hanami, pull requests merged in 2019-07, with the labels that each got.

#1006 Support both `hanami-validations` 1 and 2
  hanami.gemspec
Labels: enhancement

#994 Avoid zsh command error
  lib/hanami/templates/welcome.html.erb
Labels: bug, fix

#992 Reference Bundler as a top-level constant
  bin/hanami
  lib/hanami/environment.rb
  lib/hanami/setup.rb
Labels: fix

#1007 Drone CI
  .drone.yml
  script/test
  spec/integration/cli/server_spec.rb
  spec/integration/rake/with_minitest_spec.rb
  spec/integration/sessions_spec.rb
Labels: enhancement
