Repository hanami/hanami, pull requests merged in 2019-01, with the labels that each got.

#978 Ruby 2.6
  .travis.yml
Labels: enhancement

#974 Remove force_ssl from new app templates
  lib/hanami/cli/commands/generate/app/application.erb
  spec/integration/cli/new_spec.rb
  spec/integration/security/force_ssl_spec.rb
  spec/support/shared_examples/cli/generate/app.rb
Labels: fix

#977 `body_parsers` is deprecated but still generated into new projects
  lib/hanami/cli/commands/generate/app/application.erb
  spec/integration/body_parsers_spec.rb
  spec/integration/cli/new_spec.rb
  spec/support/shared_examples/cli/generate/app.rb
Labels: fix

#981 Fix broken 404 links to guides.hanamirb.org
  lib/hanami.rb
  lib/hanami/cli/commands/generate/app/application.erb
  lib/hanami/cli/commands/generate/app/routes.erb
  lib/hanami/cli/commands/new/Gemfile.erb
  lib/hanami/cli/commands/new/README.md.erb
  lib/hanami/cli/commands/new/config/environment.erb
  lib/hanami/configuration.rb
  lib/hanami/routes.rb
  spec/integration/cli/new_spec.rb
  spec/support/shared_examples/cli/generate/app.rb
Labels: fix

#985 Support MRI 2.5+
  CHANGELOG.md
  README.md
  hanami.gemspec
Labels: breaking-change

#986 Update copyright to 2019 [ci skip]
  LICENSE.md
  README.md
Labels: documentation

#984 Base setup for code reloading
  bin/hanami
  lib/hanami.rb
  lib/hanami/cli/commands.rb
  lib/hanami/cli/commands/command.rb
Labels: enhancement
