Repository hanami/hanami, pull requests merged in 2022-02, with the labels that each got.

#1139 Simplify `Hanami::Web::RackLogger`
  lib/hanami/application/container/boot/rack_logger.rb
  lib/hanami/web/rack_logger.rb
  spec/unit/hanami/web/rack_logger_spec.rb
Labels: enhancement

#1145 Rack Logger: Ensure to print current timestamp and indicate `ms` for elapsed time
  lib/hanami/web/rack_logger.rb
  spec/unit/hanami/web/rack_logger_spec.rb
Labels: fix

#1149 Support partial slice imports and exports
  lib/hanami/slice.rb
  spec/new_integration/container/imports_spec.rb
Labels: feature

#1150 Use concrete classes for slices, and various app/slice tidy-ups
  lib/hanami.rb
  lib/hanami/application.rb
  lib/hanami/application/slice_registrar.rb
  lib/hanami/configuration.rb
  lib/hanami/constants.rb
  lib/hanami/errors.rb
  lib/hanami/slice.rb
  spec/new_integration/application/component_provider_spec.rb
  spec/new_integration/container/imports_spec.rb
  spec/new_integration/slices_spec.rb
  spec/unit/hanami/slice_spec.rb
Labels: enhancement
